# -*- coding: utf-8 -*-
"""Linkedln_Post

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n3uW8_vIVmiaaw0tQanPx1IMUx333PcY

# LinkedIn Post Generator App

Here we will build an AI Application using Gemini, LangChain and Streamlit with the following features:

- Custom Landing Page
- LinkedIn Post Generation
- Streamlit features

## Install App and LLM dependencies
"""

!pip install langchain==0.1.12 -q
!pip install langchain-google-genai==0.0.7 -q
!pip install langchain-community==0.0.29 -q
!pip install streamlit==1.32.2 -q
!pip install pyngrok==7.1.5 -q
!pip install google-generativeai>=0.3.2 -q

"""## Load Gemini API Credentials

Here we load it from a file so we don't explore the credentials on the internet by mistake
"""

import os
from google.colab import userdata
os.environ['GOOGLE_API_KEY'] = userdata.get('GEMINI_API_KEY')

# Commented out IPython magic to ensure Python compatibility.
# %%writefile linkedin_app.py
# 
# import streamlit as st
# from langchain_google_genai import ChatGoogleGenerativeAI
# from langchain.prompts import ChatPromptTemplate
# from langchain.schema import SystemMessage, HumanMessage
# 
# st.title("LinkedIn Post Generator")
# 
# # System prompt that defines the app's behavior
# system_prompt = """You are a professional LinkedIn post generator.
# Your task is to create engaging, professional posts for LinkedIn based on the topic provided by the user.
# 
# Follow these guidelines:
# - Keep posts between 150-300 words
# - Include relevant hashtags (3-5)
# - Maintain a professional but conversational tone
# - Focus on providing value to the reader
# - Structure posts with short paragraphs for readability
# - Avoid clickbait and exaggerated claims
# 
# The user will provide a topic or idea for the post."""
# 
# # Initialize the LLM
# gemini = ChatGoogleGenerativeAI(model='gemini-2.0-flash-thinking-exp-01-21',
#                                temperature=0.7,
#                                 convert_system_message_to_human=True)
# 
# # Create the prompt template
# prompt_template = ChatPromptTemplate.from_messages([
#     ("system", system_prompt),
#     ("human", "{user_input}")
# ])
# 
# # App description
# st.markdown("### Generate professional LinkedIn posts with AI")
# st.markdown("Enter a topic or idea to get a LinkedIn post tailored to your needs.")
# 
# # Input area with specific placeholder text
# user_input = st.text_area("What would you like to post about?",
#                           placeholder="Example: Sharing my thoughts on the future of AI in healthcare",
#                           height=100)
# 
# # Generate button
# if st.button("Generate Post"):
#     if user_input:
#         with st.spinner("Creating your LinkedIn post..."):
#             # Create the prompt with the user's input
#             messages = prompt_template.format_messages(user_input=user_input)
# 
#             # Invoke the LLM
#             response = gemini.invoke(messages)
# 
#             # Display the result in a nice format
#             st.markdown("### Your LinkedIn Post:")
#             st.markdown(response.content)
# 
#             # Copy button
#             st.markdown("---")
#             st.markdown("Copy this post to your clipboard and share it on LinkedIn!")
#     else:
#         st.error("Please enter a topic for your LinkedIn post.")

!streamlit run linkedin_app.py --server.port=8990 &>./logs.txt &

from pyngrok import ngrok

# Terminate open tunnels if exist
ngrok.kill()

ngrok.set_auth_token(userdata.get('NGROK_API_KEY'))

# Open an HTTPs tunnel on port XXXX which you get from your `logs.txt` file
ngrok_tunnel = ngrok.connect(8989)
print("Streamlit App:", ngrok_tunnel.public_url)

"""## Remove running app processes"""

ngrok.kill()

!ps -ef | grep streamlit

!sudo kill -9 50727

