# -*- coding: utf-8 -*-
"""RAG_Streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A5DiHaMhiQWVneB2tgvO8YIpv7zngt5B

##**Building a Retrieval Augmented Generation (RAG) Chatbot**

Using Gemini, LangChain, and ChromaDB

This notebook will guide you through implementing the backend components of a RAG chatbot system.

##Setup and Prerequisites

First, let's install the necessary libraries.
"""

# Install required packages
!pip install langchain langchain-google-genai langchain_community pypdf chromadb sentence-transformers -q
!pip install google-generativeai pdfplumber -q

"""Next, let's import all required libraries:"""

!pip install streamlit

!pip install pyngrok

import os
import pdfplumber
import google.generativeai as genai
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_google_genai import GoogleGenerativeAIEmbeddings
from langchain_community.vectorstores import Chroma
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain.chains import ConversationalRetrievalChain
from langchain.memory import ConversationBufferMemory

from google.colab import userdata
os.environ["GOOGLE_API_KEY"] = userdata.get("GEMINI_API_KEY")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile rag_streamlit.py
# 
# import streamlit as st
# import os
# import tempfile
# import json
# from session_4_rag_backend import (
#     setup_api_key,
#     upload_pdf,
#     parse_pdf,
#     init_embedding_model,
#     embed_documents,
#     store_embeddings,
#     get_context_from_chunks,
#     query_with_full_context
# )
# 
# # Page config
# st.set_page_config(page_title="RAG Chatbot with Gemini", page_icon="📚", layout="wide")
# 
# # Session state init
# if "conversation" not in st.session_state:
#     st.session_state.conversation = []
# if "vectorstore" not in st.session_state:
#     st.session_state.vectorstore = None
# if "embedding_model" not in st.session_state:
#     st.session_state.embedding_model = None
# if "processed_files" not in st.session_state:
#     st.session_state.processed_files = []
# 
# def create_document_chunks(text, chunk_size=500, overlap=50):
#     """Splits text into overlapping chunks for better retrieval"""
#     chunks = []
#     start = 0
#     text_length = len(text)
# 
#     while start < text_length:
#         end = start + chunk_size
#         chunk = text[start:end]
#         chunks.append(chunk)
#         start += chunk_size - overlap
# 
#     return chunks
# 
# def main():
#     with st.sidebar:
#         st.title("RAG Chatbot")
#         st.subheader("Configuration")
# 
#         api_key = st.text_input("Enter Gemini API Key:", type="password")
#         if api_key and st.button("Set API Key"):
#             setup_api_key(api_key)
#             st.success("API Key set successfully!")
# 
#         st.divider()
#         st.subheader("Upload Documents")
#         uploaded_files = st.file_uploader("Upload PDF files", type="pdf", accept_multiple_files=True)
# 
#         if uploaded_files and st.button("Process Documents"):
#             process_documents(uploaded_files)
# 
#         if st.session_state.processed_files:
#             st.subheader("Processed Documents")
#             for file in st.session_state.processed_files:
#                 st.write(f"- {file}")
# 
#         st.divider()
#         with st.expander("Advanced Options"):
#             st.slider("Number of chunks to retrieve (k)", min_value=1, max_value=10, value=3, key="k_value")
#             st.slider("Temperature", min_value=0.0, max_value=1.0, value=0.2, step=0.1, key="temperature")
# 
#     st.title("Retrieval Augmented Generation Chatbot")
# 
#     if st.session_state.vectorstore is None:
#         st.info("Please upload and process documents to start chatting.")
#         with st.expander("How to use this app"):
#             st.markdown("""
#             1. Enter your Gemini API Key in the sidebar
#             2. Upload one or more PDF documents
#             3. Click "Process Documents"
#             4. Ask questions in the chat
#             """)
#     else:
#         display_chat()
#         user_query = st.chat_input("Ask a question about your documents...")
#         if user_query:
#             handle_user_query(user_query)
# 
# def process_documents(uploaded_files):
#     try:
#         progress_bar = st.sidebar.progress(0)
#         status_text = st.sidebar.empty()
# 
#         if st.session_state.embedding_model is None:
#             status_text.text("Initializing embedding model...")
#             st.session_state.embedding_model = init_embedding_model()
#             if st.session_state.embedding_model is None:
#                 st.sidebar.error("Failed to initialize embedding model.")
#                 return
# 
#         all_chunks = []
#         processed_file_names = []
# 
#         for i, uploaded_file in enumerate(uploaded_files):
#             progress = (i / len(uploaded_files)) * 100
#             progress_bar.progress(int(progress))
#             status_text.text(f"Processing {uploaded_file.name}...")
# 
#             with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmp_file:
#                 tmp_file.write(uploaded_file.getvalue())
#                 pdf_path = tmp_file.name
# 
#             pdf_file = upload_pdf(pdf_path)
#             if not pdf_file:
#                 st.sidebar.warning(f"Failed to process {uploaded_file.name}")
#                 continue
# 
#             text = parse_pdf(pdf_file)
#             if not text:
#                 st.sidebar.warning(f"Failed to extract text from {uploaded_file.name}")
#                 continue
# 
#             chunks = create_document_chunks(text)
#             if not chunks:
#                 st.sidebar.warning(f"Failed to create chunks from {uploaded_file.name}")
#                 continue
# 
#             chunks_with_metadata = [{"content": chunk, "source": uploaded_file.name} for chunk in chunks]
#             all_chunks.extend(chunks_with_metadata)
#             processed_file_names.append(uploaded_file.name)
#             os.unlink(pdf_path)
# 
#         progress_bar.progress(100)
#         status_text.text("Creating vector database...")
# 
#         if all_chunks:
#             texts = [chunk["content"] for chunk in all_chunks]
#             metadatas = [{"source": chunk["source"]} for chunk in all_chunks]
# 
#             vectorstore = store_embeddings(
#                 st.session_state.embedding_model,
#                 texts,
#                 persist_directory="./streamlit_chroma_db"
#             )
# 
#             if vectorstore:
#                 st.session_state.vectorstore = vectorstore
#                 st.session_state.processed_files = processed_file_names
#                 status_text.text("Processing complete!")
#                 st.sidebar.success(f"Successfully processed {len(processed_file_names)} documents")
#             else:
#                 st.sidebar.error("Failed to create vector database")
#         else:
#             st.sidebar.error("No valid chunks extracted from documents")
# 
#         progress_bar.empty()
#         status_text.empty()
# 
#     except Exception as e:
#         st.sidebar.error(f"Error processing documents: {str(e)}")
# 
# def handle_user_query(query):
#     if st.session_state.vectorstore is None:
#         st.error("Please process documents before asking questions")
#         return
# 
#     st.session_state.conversation.append({"role": "user", "content": query})
#     thinking_placeholder = st.empty()
#     thinking_placeholder.info("🤔 Thinking...")
# 
#     try:
#         k = st.session_state.k_value
#         temperature = st.session_state.temperature
# 
#         response, context, chunks = query_with_full_context(
#             query,
#             st.session_state.vectorstore,
#             k=k,
#             temperature=temperature
#         )
# 
#         assistant_msg = {"role": "assistant", "content": response, "context": context}
#         st.session_state.conversation.append(assistant_msg)
#         thinking_placeholder.empty()
#         display_chat()
# 
#         # Log query-response-context
#         log_data = {
#             "query": query,
#             "response": response,
#             "context": context,
#             "chunks": chunks
#         }
#         with open("rag_chat_logs.jsonl", "a", encoding="utf-8") as f:
#             f.write(json.dumps(log_data) + "\n")
# 
#     except Exception as e:
#         thinking_placeholder.empty()
#         error_msg = f"Error generating response: {str(e)}"
#         st.session_state.conversation.append({"role": "assistant", "content": error_msg})
#         display_chat()
# 
# def display_chat():
#     for message in st.session_state.conversation:
#         if message["role"] == "user":
#             with st.chat_message("user"):
#                 st.write(message["content"])
#         else:
#             with st.chat_message("assistant"):
#                 st.write(message["content"])
#                 if "context" in message and message["context"]:
#                     with st.expander("View source context"):
#                         st.text(message["context"])
# 
# def reset_conversation():
#     st.session_state.conversation = []
# 
# if __name__ == "__main__":
#     main()
#

!streamlit run rag_streamlit.py --server.port=8990 &>./logs.txt &

from pyngrok import ngrok
from google.colab import userdata

# Terminate open tunnels if exist
ngrok.kill()

ngrok.set_auth_token(userdata.get('NGROK_API_KEY'))

# Open an HTTPs tunnel on port XXXX which you get from your `logs.txt` file
ngrok_tunnel = ngrok.connect(8990)
print("Streamlit App:", ngrok_tunnel.public_url)

